version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Reynear"
    assignees:
      - "Reynear" 
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      test-dependencies:
        patterns:
          - "pytest*"
          - "*test*"
      dev-dependencies:
        patterns:
          - "ruff"
          - "mypy"
          - "bandit"
          - "safety"
      gui-dependencies:
        patterns:
          - "pyqt*"
          - "pyside*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Reynear"  # Replace with your GitHub username
    assignees:
      - "Reynear"  # Replace with your GitHub username 